"""
Business Workflow Planner - Decomposes compound multi-step business prompts into
dependency-ordered execution plans (DAGs).

Architecture:
    User Prompt → Intent Router → (compound?) → Business Workflow Planner → ExecutionPlan
    
The Business Workflow Planner uses Gemini to analyze whether a prompt contains multiple
business actions and returns an ordered list of WorkflowSteps with dependency edges.
"""

import json
from google import genai
from pydantic import BaseModel, Field
from typing import Optional
from services.retry_utils import call_with_retry


class WorkflowStep(BaseModel):
    """A single atomic step in a compound workflow execution plan."""
    step_id: str = Field(description="Unique identifier for this step, e.g. 'step_1', 'step_2'.")
    agent_type: str = Field(description="Which agent handles this step: 'master_data', 'expense', 'sales', 'reporting', 'advisory'.")
    action: str = Field(description="What action to perform, e.g. 'create_product', 'record_purchase', 'create_invoice', 'generate_report'.")
    description: str = Field(description="Human-readable description of what this step does.")
    prompt_fragment: str = Field(description="The relevant portion of the user's original prompt that this step addresses.")
    parameters_json: Optional[str] = Field(None, description="JSON string of extracted parameters for this step (entity names, amounts, quantities, etc). Example: '{\"name\": \"Dell Laptop\", \"cost_price\": 55000}'")
    depends_on: list[str] = Field(default_factory=list, description="List of step_ids that must complete before this step can execute.")

    @property
    def parameters(self) -> Optional[dict]:
        """Parse the parameters_json string into a dict."""
        if self.parameters_json:
            try:
                return json.loads(self.parameters_json)
            except (json.JSONDecodeError, TypeError):
                return {}
        return None


class ExecutionPlan(BaseModel):
    """The full execution plan generated by the Planning Agent."""
    is_compound: bool = Field(description="True if the prompt contains multiple distinct business actions requiring sequential execution.")
    reasoning: str = Field(description="Explanation of why this is or isn't a compound prompt.")
    steps: list[WorkflowStep] = Field(default_factory=list, description="Ordered list of workflow steps to execute.")


class BusinessWorkflowPlanner:
    """
    Analyzes user prompts to determine if they contain multiple business actions.
    If compound, decomposes them into a dependency-ordered execution plan.
    If simple, returns is_compound=False so the system uses the existing direct flow.
    """

    def __init__(self, client: genai.Client):
        self.client = client

    def plan(self, transcript: str, user_context: dict = None) -> ExecutionPlan:
        """
        Analyze a user prompt and generate an execution plan.
        
        Returns:
            ExecutionPlan with is_compound=False for single-action prompts,
            or is_compound=True with ordered steps for multi-action prompts.
        """
        user_context_str = json.dumps(user_context, indent=2) if user_context else "None provided"

        prompt = f"""
        You are a Business Workflow Planner for an AI CFO system. Your job is to analyze a user's prompt 
        and determine if it contains MULTIPLE distinct business actions that need to be executed in sequence.

        CLASSIFICATION RULES:

        SIMPLE (is_compound = false):
        - A single transaction: "Paid ₹5,000 rent" or "Create invoice for Acme Corp"
        - A single question: "What is my bank balance?" or "Can I afford a new car?"
        - A single action: "Create customer Rahul Technologies"
        Return is_compound=false with an empty steps list.

        COMPOUND (is_compound = true):
        - Multiple distinct business actions in one prompt
        - Examples: "Create products X, Y, Z. Then purchase 50 X from vendor A. Then sell 10 X to customer B."
        - Master data creation + transactions + reports in one prompt
        Break the prompt into ORDERED steps with proper dependencies.

        STEP TYPES (agent_type values):
        - "master_data" → Creating products, suppliers, customers, bank accounts, or other master records
        - "expense" → Recording purchases, expenses, capital injections, vendor payments
        - "sales" → Recording sales invoices, customer payments
        - "reporting" → Generating reports, balance sheets, P&L statements
        - "advisory" → Answering business advice questions

        ACTION VALUES:
        - "create_product", "create_supplier", "create_customer", "create_bank_account"
        - "record_purchase", "record_expense", "record_capital_injection", "record_vendor_payment"
        - "create_invoice", "record_customer_payment"
        - "generate_report", "generate_balance_sheet", "generate_pnl"
        - "provide_advice"

        DEPENDENCY RULES:
        - Products must be created BEFORE purchases or sales that reference them.
        - Suppliers must be created BEFORE purchases from them.
        - Customers must be created BEFORE sales to them.
        - Purchase stock-in must happen BEFORE sales stock-out of the same items.
        - Reports should be the LAST step (they reflect the final state after all transactions).

        PARAMETER EXTRACTION:
        For each step, extract relevant parameters from the prompt:
        - For products: name, cost_price, selling_price, gst_rate
        - For suppliers/customers: name, gstin, contact details
        - For purchases: items (name, quantity, unit_cost), supplier_name, credit_terms
        - For sales: items (name, quantity, unit_price), customer_name, credit_terms
        - For reports: report_type

        USER CONTEXT:
        {user_context_str}

        USER PROMPT:
        "{transcript}"
        """

        def _call():
            response = self.client.models.generate_content(
                model='gemini-3.6-flash',
                contents=prompt,
                config={
                    'response_mime_type': 'application/json',
                    'response_schema': ExecutionPlan,
                },
            )
            return ExecutionPlan(**json.loads(response.text))

        return call_with_retry(_call)
